server:
  port: 10001
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: dylanTest
#    key-store-type: PKCS12
#    key-alias: tomcat

spring:
  application:
    name: learn-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://logicer.top:3306/ds_test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: 1997o4
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
  redis:
    host: 8.131.90.159
    database: 0
    password: mylog
    port: 6379
    timeout: 0
  aop:
    proxy-target-class: false



mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#  redis:
#    cluster:
#      nodes:
#        - 172.17.93.153:7000
#        - 172.17.93.153:7001
#        - 172.17.93.153:7002
#        - 172.17.93.153:7003
#        - 172.17.93.153:7004
#        - 172.17.93.153:7005
#      max-redirects: 3
#    lettuce:
#      pool:
#        max-idle: 16
#        min-idle: 8
#        max-active: 32
testyaml:
  yamlMap:
    name: Dylan
    age: 24
    gender: man